export default {
  appname: 'Crystal Dash',
  prospects: 'Prospects',
  dashboard: 'Dashboard',
  contacts: 'Contacts',
  calendar: 'Calendar',
  notifications: 'Notifications',
  add_note: 'Add Note',
  add_Contact: 'Add Contact',
  all: 'All',
  call_list: 'Call List',
  clients: 'Clients',
  leads: 'Leads',
  name: 'Name',
  company: 'Company',
  contact: 'Contact',
  potential: 'Potential',
  home: 'Home',
  appointments: 'Appointments',
  opportunity: 'Opportunity',
  sales_report: 'Sales Report',
  settings: 'Settings',
  logout: 'Logout',
  call_lists: 'Call Lists',
  existing_plan: 'View Your Existing Plan',
  view_invoice: 'View Invoice',
  outstanding_payment: 'Outstanding Payments',
  past_invoice: 'Past Invoce',
  payment_methods: 'Payment Methods',
  browse_add_on: 'Browse Add-on',
  latest_promotion: 'Latest Promotion',
  photo_catelouge: 'Photo Catelouge',
  account_settings: 'Account Settings',
  intro: 'Intro',
  fact_find: 'Fact Find',
  signup_info: 'Sign up Info',
  proposal: 'Proposal',
  add_Event: 'Add Event',
  schedule_appointment: 'New Appointment',
  edit_appointment:'Edit Appointment',
  details: 'Details',
  follow_up: 'Follow-ups',
  contact_profile: 'Contact Profile',
  schedule_followup: 'Schedule Followup',
  view_all_follow: 'View All Follow-ups',
  prospects_follow: 'Prospects Follow-ups',
  client_follow: 'Client Follow-ups',
  lead_follow: 'Lead Follow-ups',
  notification: 'Notifications',
  api_token: 'api_token',
  selectedCompany: 'selectedCompany',

  TRUE: true,
  FALSE: false,
  SUCCESS: true,
  ALREADY: 'already',
  LOGGEDIN: 'loggedIn',
  USERINFO: 'userinfo',
  FoodAPI: 'FoodAPI',
  WARNING: false,
  message: 'Something went wrong',
  FACEBOOK: 'facebook',
  user_like: 'true',
  user_unlike: 'false'
};